version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: meeting-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: meeting_room
      TZ: Asia/Seoul
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2_data.sql

volumes:
  mysql_data:
